Repository 202309-EKTA-JO-FSW/capstone-YUMFINITY, pull requests merged in 2024-02, with the labels that each got.

#3 created user schema and model, with unit tests
  server/server/Models/user.js
  server/server/__tests__/models-tests/user.test.js
Labels: feature

#5 created Cart mongoose schema and model, with unit tests
  server/server/Models/cart.js
  server/server/__tests__/models-tests/cart.test.js
Labels: feature

#8 created Order mongoose schema and model, with unit tests
  server/server/Models/order.js
  server/server/__tests__/models-tests/order.test.js
Labels: feature

#10 create restaurant mongoose schema and model
  server/server/Models/restaurant.js
Labels: feature

#15 fix error message in models for location, fix phoneNumber in user
  server/server/Models/order.js
  server/server/Models/restaurant.js
  server/server/Models/user.js
  server/server/__tests__/models-tests/user.test.js
Labels: enhancement

#12 created review model, with test
  server/server/Models/review.js
  server/server/__tests__/models-tests/review.test.js
Labels: feature

#21 fixes for order and restaurant schemas
  server/server/Models/order.js
  server/server/Models/restaurant.js
Labels: enhancement, fix

#18 create item mongoose schema and model
  server/server/Models/item.js
Labels: feature

#22 Public API GET restaurant list route and controller
  server/package-lock.json
  server/package.json
  server/server/Controllers/restaurant.js
  server/server/Controllers/restaurant.utils.js
  server/server/Routes/restaurant.js
  server/server/Routes/v1.js
  server/yarn.lock
Labels: feature

#25 Public API POST sign in route and controller
  server/.env
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/server/Controllers/signIn.js
  server/server/Routes/sign.js
  server/server/Routes/v1.js
  server/yarn.lock
Labels: feature

#24 Public API POST sign up route and controller
  package-lock.json
  server/package.json
  server/server/Controllers/userController.js
  server/server/Models/item.js
  server/server/Routes/signup.js
Labels: feature

#27 fix integration test
  .github/workflows/CI.yml
  server/Dockerfile
  server/server/__tests__/models-tests/cart.test.js
  server/server/__tests__/models-tests/order.test.js
  server/server/db/connection.js
Labels: bug, fix

#31 some fixes and files structure enhancements
  package.json
  server/package.json
  server/server/Controllers/.gitkeep
  server/server/Controllers/restaurantController.js
  server/server/Controllers/signIn.js
  server/server/Controllers/signingController.js
  server/server/Controllers/userController.js
  server/server/Middlewares/.gitkeep
  server/server/Models/.gitkeep
  server/server/Models/user.js
  server/server/Routes/.gitkeep
  server/server/Routes/restaurant.js
  server/server/Routes/restaurantRoutes.js
  server/server/Routes/sign.js
  server/server/Routes/signRoutes.js
  server/server/Routes/v1.js
  server/server/__tests__/models-tests/user.test.js
  server/server/utils/createTokens.js
  server/server/utils/locationFilter.js
  server/server/utils/pagination.js
Labels: enhancement, fix

#30 create item GET request controller with filter functionality
  server/server/Controllers/item.js
Labels: feature

#34 JWT authentication implementation with access and refresh tokens
  package-lock.json
  server/package-lock.json
  server/package.json
  server/server/Controllers/signingController.js
  server/server/Middlewares/passportAuthMiddleware.js
  server/server/Routes/signRoutes.js
  server/server/configs/passport.js
  server/server/index.js
  server/server/utils/createTokens.js
  server/yarn.lock
Labels: feature

#33 add admin CRUD on item model
  server/server/Controllers/adminCrud.js
  server/server/Routes/admin.js
Labels: feature
