Repository 202309-EKTA-JO-FSW/capstone-YUMFINITY, pull requests merged in 2024-03, with the labels that each got.

#42 Created admin authorization middleware
  server/server/Middlewares/authorizeAdmin.js
  server/server/Middlewares/passportAuthMiddleware.js
  server/server/index.js
Labels: feature

#49 admin routing and controller enhancement
  server/server/Controllers/adminController.js
  server/server/Controllers/adminCrud.js
  server/server/Routes/admin.js
  server/server/Routes/adminRoutes.js
  server/server/Routes/v1.js
  server/server/utils/pagination.js
Labels: enhancement, fix

#47 add customer controller- CRUD on user
  server/server/Controllers/customerCrud.js
Labels: feature

#53 created admin controller to retrieve current-delivering-orders
  server/server/Controllers/adminController.js
  server/server/Routes/adminRoutes.js
Labels: enhancement, feature

#48 created customer controller and routes- CRUD on order
  server/server/Controllers/customerController.js
  server/server/Models/review.js
  server/server/Routes/customerRoutes.js
  server/server/Routes/v1.js
Labels: enhancement, feature

#55 created admin controller to update the order status
  server/server/Controllers/adminController.js
  server/server/Routes/adminRoutes.js
Labels: enhancement, feature

#56 general enhancements and route organization
  server/server/Controllers/adminController.js
  server/server/Controllers/customerController.js
  server/server/Controllers/customerCrud.js
  server/server/Controllers/item.js
  server/server/Controllers/signingController.js
  server/server/Routes/adminRoutes.js
  server/server/Routes/signRoutes.js
  server/server/Routes/v1.js
Labels: enhancement, fix

#57 deleted unnecessary /:id from some routes
  server/server/Routes/adminRoutes.js
Labels: fix

#61 Setup mongoDB Atlas connection
  server/.env
  server/server/db/connection.js
Labels: feature

#59 user cart CRUD - routes and controllers
  server/server/Controllers/customerController.js
  server/server/Routes/customerRoutes.js
Labels: feature

#62 Add signout private route
  server/server/Controllers/signingController.js
  server/server/Routes/signRoutes.js
  server/server/Routes/v1.js
Labels: feature

#71 Setup prettier tailwind plugin for frontend, general Backend fixes and formatting
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  server/server/Controllers/customerController.js
  server/server/Controllers/signingController.js
  server/server/Routes/customerRoutes.js
  server/server/Routes/signRoutes.js
  server/server/Routes/v1.js
Labels: feature, fix

#73 create initial footer
  client/public/logo.svg
  client/src/app/components/Footer.js
  client/src/app/components/Logo.jsx
  client/src/app/layout.js
  package-lock.json
  package.json
Labels: feature

#74 create contact form
  client/package.json
  client/src/app/ContactPage/page.js
  package-lock.json
  package.json
Labels: feature

#86 create 404 error page
  client/src/app/not-found.js
Labels: feature

#84 create sign in page
  client/src/app/SignIn/page.js
Labels: feature

#87 created landing page
  client/src/app/components/LandingPage/LandingPageNavbar.jsx
  client/src/app/components/LandingPage/LandingPageNavbar.module.css
  client/src/app/components/LandingPage/Search.jsx
  client/src/app/components/LandingPage/Section.jsx
  client/src/app/components/LandingPage/Services.jsx
  client/src/app/components/LandingPage/background-mobile.jpeg
  client/src/app/components/LandingPage/background.webp
  client/src/app/page.js
Labels: feature

#82 create sign up page
  client/src/app/SignUp/page.js
Labels: feature

#91 Review Card
  client/src/app/components/Restaurant/ReviewCard.jsx
Labels: feature

#90 edit sign in page
  client/src/app/SignIn/page.js
Labels: enhancement

#93 editing and enhancing responsivity
  client/src/app/SignIn/page.js
  client/src/app/SignUp/page.js
Labels: enhancement, fix

#94 Create profile page
  client/src/app/profile/components/DeleteUser.jsx
  client/src/app/profile/components/PastOrderCard.jsx
  client/src/app/profile/components/PastOrders.jsx
  client/src/app/profile/components/accountDetails.jsx
  client/src/app/profile/components/currentOrder.jsx
  client/src/app/profile/components/profile-placeholder.jpg
  client/src/app/profile/page.js
Labels: feature

#98 edits on Linking buttons hrefs, edits on layout
  client/src/app/SignIn/page.js
  client/src/app/SignUp/page.js
  client/src/app/components/Footer.js
  client/src/app/components/LandingPage/LandingPageNavbar.jsx
  client/src/app/components/LandingPage/Services.jsx
  client/src/app/components/Navbar.module.css
  client/src/app/components/Restaurant/ReviewCard.jsx
  client/src/app/contact-us/page.js
  client/src/app/restaurants/page.js
Labels: enhancement, fix

#96 created single restaurant page
  client/src/app/singleRestaurantPage/HoverMe.jsx
  client/src/app/singleRestaurantPage/Pagination.jsx
  client/src/app/singleRestaurantPage/ReviewsOrItems.jsx
  client/src/app/singleRestaurantPage/background.jpg
  client/src/app/singleRestaurantPage/page.js
Labels: feature

#95 Created Navbar
  client/src/app/components/Navbar.jsx
  client/src/app/layout.js
Labels: feature

#103 Configure Sign in integration with backend
  client/package-lock.json
  client/package.json
  client/src/app/SignIn/GoogleSignIn.jsx
  client/src/app/SignIn/SignInForm.jsx
  client/src/app/SignIn/page.js
  client/src/app/SignIn/signin.module.css
  client/src/app/components/LandingPage/LandingPageNavbar.jsx
  client/src/app/components/Navbar.jsx
  client/src/app/layout.js
  client/src/app/utils/contextProvider.jsx
  server/server/Controllers/signingController.js
Labels: feature

#104 fixed navbar on mobiles; enhanced footer layout; hyperlink enhancements
  client/src/app/SignUp/page.js
  client/src/app/components/Footer.js
  client/src/app/components/Navbar.jsx
  client/src/app/components/Navbar.module.css
  client/src/app/contact-us/page.js
  client/src/app/not-found.js
Labels: enhancement, fix

#100 create Shopping Cart Component
  client/src/app/singleRestaurantPage/ShoppingCart.jsx
Labels: feature

#108 Change navbar overflow css rules for mobiles
  client/src/app/components/Navbar.jsx
  client/src/app/components/Navbar.module.css
Labels: fix

#110 Sign Up page integration with Backend
  client/src/app/SignUp/SignUpForm.jsx
  client/src/app/SignUp/page.js
  client/src/app/SignUp/signup.module.css
Labels: feature

#111 Sign In integration fixes
  client/src/app/SignIn/SignInForm.jsx
  client/src/app/SignIn/page.js
Labels: fix

#115 added how it works section in landing page
  client/src/app/components/LandingPage/Process.jsx
  client/src/app/components/LandingPage/Services.jsx
  client/src/app/page.js
Labels: enhancement, feature

#106 created checkout page with payment methods
  client/src/app/checkout/PaymentForm.jsx
  client/src/app/checkout/PaymentMethod.jsx
  client/src/app/checkout/ShoppingCart.jsx
  client/src/app/checkout/page.js
Labels: enhancement, feature

#116 edit on checkout page
  client/src/app/checkout/page.js
Labels: enhancement

#123 Sign in with Google functionality
  client/src/app/SignIn/GoogleSignIn.jsx
  client/src/app/SignIn/SignInForm.jsx
  client/src/app/SignIn/page.js
  client/src/app/SignUp/SignUpForm.jsx
  client/src/app/components/GoogleSignIn.jsx
  server/server/Controllers/signingController.js
  server/server/configs/passport.js
Labels: feature

#119 Restaurants Page integration
  client/src/app/components/Restaurant/RestaurantCard.jsx
  client/src/app/restaurants/RestaurantsList.jsx
  client/src/app/restaurants/SearchAndList.jsx
  client/src/app/restaurants/SearchRestaurants.jsx
  client/src/app/restaurants/page.js
Labels: feature

#121 Home page search integration
  client/src/app/components/LandingPage/Search.jsx
Labels: feature

#124 Single Restaurant Page integration
  client/src/app/components/Restaurant/ItemCard.jsx
  client/src/app/components/Restaurant/RestaurantCard.jsx
  client/src/app/components/Restaurant/ReviewCard.jsx
  client/src/app/restaurant/[id]/HoverMe.jsx
  client/src/app/restaurant/[id]/InfoCards.jsx
  client/src/app/restaurant/[id]/MainPage.jsx
  client/src/app/restaurant/[id]/Pagination.jsx
  client/src/app/restaurant/[id]/ReviewsOrItems.jsx
  client/src/app/restaurant/[id]/ShoppingCart.jsx
  client/src/app/restaurant/[id]/background.jpg
  client/src/app/restaurant/[id]/page.js
  client/src/app/restaurants/page.js
  client/src/app/singleRestaurantPage/ShoppingCart.jsx
  client/src/app/singleRestaurantPage/page.js
  server/server/Controllers/restaurantController.js
Labels: feature

#101 admin dashboard
  client/src/app/admin/dashboard/AddItem.jsx
  client/src/app/admin/dashboard/AddRestaurant.jsx
  client/src/app/admin/dashboard/Dashboard.jsx
  client/src/app/admin/dashboard/DeleteDialogBox.jsx
  client/src/app/admin/dashboard/EditItem.jsx
  client/src/app/admin/dashboard/EditRestaurant.jsx
  client/src/app/admin/dashboard/ItemRow.jsx
  client/src/app/admin/dashboard/RestaurantRow.jsx
  client/src/app/admin/dashboard/ViewItems.jsx
  client/src/app/admin/dashboard/ViewRestaurants.jsx
  client/src/app/admin/dashboard/page.js
  client/src/app/utils/refreshAccessToken.jsx
  server/server/Routes/adminRoutes.js
  server/server/Routes/v1.js
Labels: feature

#126 Cart integration
  client/src/app/components/Restaurant/ItemCard.jsx
  client/src/app/restaurant/[id]/MainPage.jsx
  client/src/app/restaurant/[id]/ReviewsOrItems.jsx
  client/src/app/restaurant/[id]/ShoppingCart.jsx
  client/src/app/restaurant/[id]/ShoppingCartRow.jsx
  client/src/app/restaurant/[id]/page.js
  server/server/Controllers/customerController.js
Labels: feature

#128 Deploy backend server on Render
  server/.env
  server/package.json
  server/server/configs/passport.js
  server/server/index.js
Labels: feature

#130 Migrating to deployed server
  client/src/app/SignIn/page.js
  client/src/app/SignUp/page.js
  client/src/app/admin/dashboard/page.js
  client/src/app/components/GoogleSignIn.jsx
  client/src/app/components/Test.jsx
  client/src/app/restaurant/[id]/page.js
  client/src/app/restaurants/page.js
  client/src/app/utils/refreshAccessToken.jsx
  server/server/configs/passport.js
Labels: feature

#134 Configure build command
  client/package.json
Labels: feature

#136 General enhancements
  client/public/logo.svg
  client/src/app/about/FAQ.jsx
  client/src/app/about/HeroSection.jsx
  client/src/app/about/JoinTeam.jsx
  client/src/app/about/hero.jpg
  client/src/app/about/page.js
  client/src/app/admin/dashboard/Dashboard.jsx
  client/src/app/admin/dashboard/ViewItems.jsx
  client/src/app/admin/dashboard/ViewRestaurants.jsx
  client/src/app/components/LandingPage/Process.jsx
  client/src/app/components/Navbar.jsx
  client/src/app/components/Restaurant/RestaurantCard.jsx
  client/src/app/favicon.ico
  client/src/app/profile/components/DeleteUser.jsx
  client/src/app/profile/components/PastOrderCard.jsx
  client/src/app/profile/components/PastOrders.jsx
  client/src/app/profile/components/accountDetails.jsx
  client/src/app/profile/components/currentOrder.jsx
  client/src/app/restaurant/[id]/InfoCards.jsx
  client/src/app/restaurant/[id]/MainPage.jsx
  client/src/app/restaurant/[id]/ShoppingCart.jsx
  client/src/app/restaurant/[id]/ShoppingCartRow.jsx
  client/src/app/restaurants/RestaurantsList.jsx
  client/src/app/restaurants/SearchRestaurants.jsx
Labels: feature

#135 added README file
  README.md
Labels: documentation

#137 General enhancements and integration
  client/src/app/about/HeroSection.jsx
  client/src/app/about/page.js
  client/src/app/checkout/PaymentForm.jsx
  client/src/app/checkout/PaymentMethod.jsx
  client/src/app/checkout/ShoppingCart.jsx
  client/src/app/checkout/page.js
  client/src/app/favicon.ico
  server/server/Controllers/signingController.js
  server/server/index.js
Labels: enhancement, fix
